version: "3.9"

services:
  airflowtutorial:
    build: .
    image: airflowtutorial:2.7.1
    restart: unless-stopped
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone

  smtp:
    image: bytemark/smtp
    restart: always